parameters:
    gordalina_mixpanel.registry.class: Gordalina\MixpanelBundle\ManagerRegistry
    gordalina_mixpanel.flusher.class: Gordalina\MixpanelBundle\Mixpanel\Flusher
    gordalina_mixpanel.expression_language.class: Symfony\Component\ExpressionLanguage\ExpressionLanguage

    gordalina_mixpanel.authentication.listener.class: Gordalina\MixpanelBundle\EventListener\AuthenticationListener
    gordalina_mixpanel.controller.listener.class: Gordalina\MixpanelBundle\EventListener\ControllerListener
    gordalina_mixpanel.finish_request.listener.class: Gordalina\MixpanelBundle\EventListener\FinishRequestListener

    gordalina_mixpanel.security.authentication.class: Gordalina\MixpanelBundle\Security\Authentication
    gordalina_mixpanel.security.user_data.class: Gordalina\MixpanelBundle\Security\UserData

    gordalina_mixpanel.data_collector.class: Gordalina\MixpanelBundle\DataCollector\MixpanelDataCollector
